# Generated by Django 4.2.1 on 2023-05-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('url', models.URLField()),
                ('html_url', models.URLField()),
                ('state', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('merge_commit_sha', models.CharField(max_length=40)),
                ('user_login', models.CharField(max_length=100)),
                ('user_avatar_url', models.URLField()),
            ],
            options={
                'db_table': 'pull_requests',
            },
        ),
    ]
