# Generated by Django 4.2.1 on 2023-05-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullrequest',
            old_name='user_login',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='html_url',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='user_avatar_url',
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='action',
            field=models.CharField(choices=[('opened', 'Open'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Close')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
