# Generated by Django 4.2.1 on 2023-05-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='merge_commit_sha',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
