# Generated by Django 4.2.1 on 2023-05-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_webhooks', '0002_alter_pullrequest_merge_commit_sha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
